# Docker Compose - Secure Configuration
version: "3.8"

services:
  weather-app-secure:
    build:
      context: .
      dockerfile: Dockerfile.secure
    ports:
      - "3000:5173"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

    # Security configurations
    security_opt:
      - no-new-privileges:true

    # Resource limits to prevent DoS
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          memory: 256M

    # Read-only root filesystem
    read_only: true

    # Temporary filesystem for writable areas
    tmpfs:
      - /tmp:noexec,nosuid,size=100m

    # Drop all capabilities and only add necessary ones
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

    # Network security
    networks:
      - app-network

  # For comparison - vulnerable version
  weather-app-vulnerable:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:5173"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    # Set to false for external access (demo purposes)
    # Set to true for complete isolation
    internal: false
